### PR TITLE
Fixes MSDistributeTests compilation error

### PR DESCRIPTION
**Pull request by bmourat**

### CODE REVIEW

**Comment by TroubleMakerBen** [comment]
Looks good. What's really odd is that I swear that I tried this earlier and it didn't work. I've cherrypicked that change for #752 to make it pass the unit tests.

**Comment by TroubleMakerBen** [comment]
The tests fail because of an error that was present in #752. I updated #752 with this change here, so I'm closing this PR.
